### ISSUE TITLE
Character Extensions turn character element into action element

### ISSUE THREAD

**Issue by ottumm** [vilcans/screenplain#11]
If I include a parenthetical character extension after a character name like this:

```
SPECIALIST O'HARA (tensely)
Wire cutters.
```

it will be rendered into this HTML:

```
<div class="action"><p>SPECIALIST O'HARA (tensely)<br/>Wire cutters.</p></div>
```

It seems like it should be rendered as a `class="character"` according to [the documentation](http://fountain.io/syntax#section-character), but I may be missing something.

**Comment by rnkn** [comment]
Sorry to revive an old issue, but I believe the spec changed with Fountain 1.1 to permit lowercase “character extensions". See https://fountain.io/syntax#section-changes

> Deprecated in Fountain 1.1:
> - "Character Extensions"--the parenthetical notations that follow a character name on the same line--are no longer required to be uppercase.

I agree that the top example should be:
~~~
SPECIALIST O’HARA
(tensely)
Wire cutters.
~~~
But given the 1.1 spec this should be permitted:
~~~
SPECIALIST O’HARA (cont’d)
(tensely)
Wire cutters.
~~~

Also, the lowercase looks much nicer 🙂
