### ISSUE TITLE
PDF exports Scene Headings as Bold and Underlined

### ISSUE THREAD

**Issue by charneykaye** [vilcans/screenplain#14]
This seems to be the Hollywood standard.
Perhaps this could be activated with a command-line option?

**Comment by vilcans** [comment]
Good question. I have the impression that contemporary scripts often use bold and underlined scene headings. A command-line flag may be the solution.

BTW, it's a bit odd of ReportLab to require HTML strings for this, but that seems to be the way it's supposed to work.
