### ISSUE TITLE
Usage of h1-h5 in HTML export

### ISSUE THREAD

**Issue by cweiske** [vilcans/screenplain#26]
The CSS contains code for h1 to h5, but [the fountain file I used](http://cweiske.de/schneewittchen/schneewittchen.fountain) did only generate `<h6>` tags. Why?

**Comment by vilcans** [comment]
h1-h5 are used for the synopsis levels. See the synopsis feature.

**Comment by cweiske** [comment]
Ah, http://fountain.io/syntax#section-sections
