### ISSUE TITLE
Suggestion for README: other markdown process for HTML -> PDF

### ISSUE THREAD

**Issue by Alok** [vilcans/screenplain#34]
PDF output isn't currently supported, but HTML is. I think that any other markdown processor could take the HTML (since it has the necessary styling info), and output a nice PDF document. If you use [pandoc](http://pandoc.org/), then you can convert to just about anything.

**Comment by vilcans** [comment]
PDF output is actually supported in the command-line tool. I haven't had the time to enable it for the online version.
