### ISSUE TITLE
Editorial "Fountain to PDF" workflow using Screenplain exposes [[Notes]]

### ISSUE THREAD

**Issue by bjdavis22** [vilcans/screenplain#37]
All of my notes in double brackets are exposed in The Editorial PDF generated using Screenplain. This is the workflow baked into editorial, but must be installed. Anyway to fix this? I do not have issues on Highland beta 2.0, logline or slugline.

Also, supporting more than six hastags for sections would be useful as well. I could easily go ten to twelve deep. MovieMagic Screenwriter supported over thirty and at one point I used them all.

**Comment by vilcans** [comment]
Actually, Screenplain doesn't support notes currently, so I'm treating this as a request for to implement notes.

**Comment by bronzehedwick** [comment]
This is what the OP was talking about, I think https://fountain.io/syntax#section-notes
