### ISSUE TITLE
How can I use screenplain in my python script?

### ISSUE THREAD

**Issue by raymestalez** [vilcans/screenplain#39]
Hi! I am trying to use screenplain in my python script. 

I want to pass it a fountain screenplay as a string, and get html(without the head/body tags, just screenplay) in return.

Can you help me out?

**Comment by vilcans** [comment]
Have a look at what main.py does. Basically, it calls fountain.parse, passing the Fountain source as an input stream (if you have it in a string you can use StringIO, or maybe call parse_lines instead). Then call screenplain.export.html.convert with the script. It expects an output stream, so if you want the output in a string, use StringIO.

I hope this helps.

**Comment by raymestalez** [comment]
Awesome, thank you so much!
