### ISSUE TITLE
Javascript library

### ISSUE THREAD

**Issue by eckerdan** [vilcans/screenplain#44]
A javascript library for web app support.

**Comment by vilcans** [comment]
Yes, that would be nice, but it's not a goal for the Screenplain Python project. Try googling for "fountain javascript" - it gives a few hits. It's also possible to compile Screenplain into Javascript. I have seen it done, but I don't know what tool they used.

**Comment by eckerdan** [comment]
I've googled it many times and the best one I found was fountain.js but it
isn't working for me.

If a web version is not the goal, how was the web page made? If it was made
by compiling it to js, how can you do this?

Am 31.10.2017 8:34 nachm. schrieb "Martin Vilcans" <notifications@github.com

**Comment by vilcans** [comment]
The web version runs the Python code on the server.
