### ISSUE TITLE
Any chance of merging and releasing Python 3 support?

### ISSUE THREAD

**Issue by jpyams** [vilcans/screenplain#45]
I see that there is a python3 branch where some work was done to make screenplain work in Python 3.  Is there any chance of these improvements getting merged to master and released to PyPI?

If there's further work that needs to be done I'm more than happy to help.

Also, thanks for this awesome little script!

**Comment by vilcans** [comment]
I started on a version that worked on both Python 2 and Python 3. It was some time ago, and now I'm not sure what the state of that branch is. Now that Python 2 is deprecated maybe it's time to simply switch to only supporting Python 3. I've been slow on adopting Python 3 myself, but maybe it's time to take the jump. :-)

If you want, you can try the status of the unit tests in the python3 branch to see the state of it.

**Comment by jpyams** [comment]
Removing Py2 support would definitely simplify the doctest handling.

Unit tests in the python3 branch work fine.  After merging the latest changes in, screenplain on Python 3 works like a charm.  With a slight tweak the unit tests also pass in both Python 2 and 3.

I'll create a pull request to merge the python3 branch changes.

**Comment by vilcans** [comment]
Done merging your changes. Thanks! Now on to figuring out how to release a Python 3 package on Pypi...

**Comment by vilcans** [comment]
Released as version 0.8.0.
