### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by vilcans** [vilcans/screenplain#54]
Now that the Python Foundation have closed all support for Python 2, it's about time to port Screenplain to Python 3.

Finalize the port to Python 3 and make that the new master branch. Stop supporting Python 2 altogether in new versions. Making the same code work with both 2 and 3 was such a hassle last time I tried.

**Comment by jstasiak** [comment]
FYI the current master branch with https://github.com/vilcans/screenplain/pull/56 applied works fine for me on Python 3.8.
