### ISSUE TITLE
Module doesn't run without dunders around main.py

### ISSUE THREAD

**Issue by karlsaintlucy** [vilcans/screenplain#64]
Hiya, I wasn't able to run screenplain as expected until I renamed main.py to `__main__.py`.

**Comment by vilcans** [comment]
That does not sound right, and doesn't make sense. (`__init__.py` is a magic file name in Python, but `__main__.py` has no significance.) After installing Screenplain with `pip install screenplain` you should be able to just run the command `screenplain` to run it.

**Comment by karlsaintlucy** [comment]
Hiya,

Yup, that didn't work; I got an error in the Windows terminal that said it
couldn't find __main__.py; I can give you the stack trace if you'd like.
Not sure why! But I renamed it and was able to get it to work. Not sure why
that would be an issue, but there it is.

Thanks,

[image: logo_transparent_background.png] <http://karlsaintlucy.com/>
(they/them/their)
Clippings <https://www.clippings.me/karlsaintlucy> • Facebook
<https://www.facebook.com/karlsaintlucy/> • Twitter
<https://twitter.com/karlsaintlucy>
Signal: +1 (918) 704-3150
Write me securely via FlowCrypt <https://flowcrypt.com/me/karlsaintlucy>

**Comment by vilcans** [comment]
Can you attach the commands and all output?
